# Generated by Django 5.2.8 on 2025-12-02 15:00

import django.core.validators
import re
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0003_alter_footerbottommenu_site_mainmenu"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mainmenu",
            options={"verbose_name": "Main menu", "verbose_name_plural": "Main menus"},
        ),
        migrations.AlterField(
            model_name="footerbottommenu",
            name="items",
            field=wagtail.fields.StreamField(
                [("link", 6)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("page", "Page"),
                                ("external_url", "External URL"),
                                ("document", "Document"),
                                ("anchor", "Anchor link"),
                            ],
                            "help_text": "Select the type of link.",
                            "label": "Link type",
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "help_text": "Link to a page of this site. Use either this, the document, or the external URL parameter.",
                            "label": "Page",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {
                            "help_text": "Use either this, the external URL or the page parameter.",
                            "label": "Document",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Use either this, the document or the page parameter.",
                            "label": "External URL",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Link to an anchor block on the page. Allowed characters: A-Z, a-z, 0-9, - and _.",
                            "label": "Anchor ID",
                            "required": False,
                            "validators": [
                                django.core.validators.RegexValidator(
                                    re.compile("^[-a-zA-Z0-9_]+\\Z"),
                                    "Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.",
                                    "invalid",
                                )
                            ],
                        },
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "If this field is empty, the title of the linked page or document will be used.",
                            "label": "Link label",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("link_type", 0),
                                ("page", 1),
                                ("document", 2),
                                ("external_url", 3),
                                ("anchor", 4),
                                ("text", 5),
                            ]
                        ],
                        {"label": "Link"},
                    ),
                },
                verbose_name="Menu items",
            ),
        ),
        migrations.AlterField(
            model_name="mainmenu",
            name="items",
            field=wagtail.fields.StreamField(
                [("link", 6), ("submenu", 10), ("megamenu", 18)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("page", "Page"),
                                ("external_url", "External URL"),
                                ("document", "Document"),
                                ("anchor", "Anchor link"),
                            ],
                            "help_text": "Select the type of link.",
                            "label": "Link type",
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "help_text": "Link to a page of this site. Use either this, the document, or the external URL parameter.",
                            "label": "Page",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {
                            "help_text": "Use either this, the external URL or the page parameter.",
                            "label": "Document",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Use either this, the document or the page parameter.",
                            "label": "External URL",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Link to an anchor block on the page. Allowed characters: A-Z, a-z, 0-9, - and _.",
                            "label": "Anchor ID",
                            "required": False,
                            "validators": [
                                django.core.validators.RegexValidator(
                                    re.compile("^[-a-zA-Z0-9_]+\\Z"),
                                    "Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.",
                                    "invalid",
                                )
                            ],
                        },
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "If this field is empty, the title of the linked page or document will be used.",
                            "label": "Link label",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("link_type", 0),
                                ("page", 1),
                                ("document", 2),
                                ("external_url", 3),
                                ("anchor", 4),
                                ("text", 5),
                            ]
                        ],
                        {"label": "Link"},
                    ),
                    7: ("wagtail.blocks.CharBlock", (), {"label": "Submenu label", "required": True}),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("link_type", 0),
                                ("page", 1),
                                ("document", 2),
                                ("external_url", 3),
                                ("anchor", 4),
                                ("text", 5),
                            ]
                        ],
                        {},
                    ),
                    9: ("wagtail.blocks.StreamBlock", [[("link", 8)]], {"label": "Links", "max_num": 8, "min_num": 1}),
                    10: ("wagtail.blocks.StructBlock", [[("label", 7), ("links", 9)]], {"label": "Submenu"}),
                    11: ("wagtail.blocks.CharBlock", (), {"label": "Mega menu label", "required": True}),
                    12: ("wagtail.blocks.CharBlock", (), {"label": "Description", "required": False}),
                    13: ("wagtail.blocks.CharBlock", (), {"default": "See the whole section", "label": "Link label"}),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("link_type", 0),
                                ("page", 1),
                                ("document", 2),
                                ("external_url", 3),
                                ("anchor", 4),
                                ("text", 13),
                            ]
                        ],
                        {"label": "Main link", "required": False},
                    ),
                    15: ("wagtail.blocks.CharBlock", (), {"label": "Column label", "required": True}),
                    16: ("wagtail.blocks.StructBlock", [[("label", 15), ("links", 9)]], {"label": "Column"}),
                    17: (
                        "wagtail.blocks.StreamBlock",
                        [[("column", 16)]],
                        {"label": "Columns", "max_num": 4, "min_num": 1, "required": True},
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 11), ("description", 12), ("main_link", 14), ("columns", 17)]],
                        {"label": "Mega menu"},
                    ),
                },
                verbose_name="Menu items",
            ),
        ),
        migrations.AlterField(
            model_name="topmenu",
            name="items",
            field=wagtail.fields.StreamField(
                [("link", 7)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("page", "Page"),
                                ("external_url", "External URL"),
                                ("document", "Document"),
                                ("anchor", "Anchor link"),
                            ],
                            "help_text": "Select the type of link.",
                            "label": "Link type",
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "help_text": "Link to a page of this site. Use either this, the document, or the external URL parameter.",
                            "label": "Page",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {
                            "help_text": "Use either this, the external URL or the page parameter.",
                            "label": "Document",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Use either this, the document or the page parameter.",
                            "label": "External URL",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Link to an anchor block on the page. Allowed characters: A-Z, a-z, 0-9, - and _.",
                            "label": "Anchor ID",
                            "required": False,
                            "validators": [
                                django.core.validators.RegexValidator(
                                    re.compile("^[-a-zA-Z0-9_]+\\Z"),
                                    "Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.",
                                    "invalid",
                                )
                            ],
                        },
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "If this field is empty, the title of the linked page or document will be used.",
                            "label": "Link label",
                            "required": False,
                        },
                    ),
                    6: (
                        "content_manager.blocks.buttons_links.IconPickerBlock",
                        (),
                        {"label": "Icon", "required": False},
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("link_type", 0),
                                ("page", 1),
                                ("document", 2),
                                ("external_url", 3),
                                ("anchor", 4),
                                ("text", 5),
                                ("icon_class", 6),
                            ]
                        ],
                        {"label": "Link"},
                    ),
                },
                verbose_name="Menu items",
            ),
        ),
    ]
